### ISSUE TITLE
Should it cleanse partial matches?

### ISSUE THREAD

**Issue by remy** [shwetasabne/profanity-cleanser#1]
The string `'We tried to assimilate the borg'` gets cleansed to `'We tried to ***imilate the borg'` - is this expected? I'm inclined to think not, so the matcher would need to check for breaks first. I have similar code to this that I could PR if you like.

**Comment by shwetasabne** [comment]
Thanks a lot for the feedback @remy !

You are right ! I have just pushed new changes to account for this scenario. 

I also found one another bug where I was not replacing all occurrences of the same bad word in a string. 
Eg : "This is ass ass ass" was becoming "This is **\* ass ass". The PR also addresses this issue. 

2 new testcases have been added here : https://github.com/shwetasabne/profanity-cleanser/blob/master/test/acceptance/filter.js#L89

Let me know what you think !

**Comment by remy** [comment]
As per my emoji's I dropped on your comment - thanks!
